language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py26-django1.5-drf2.3.8
    - TOX_ENV=py26-django1.5-drf2.4.3
    - TOX_ENV=py26-django1.5-drf3.0
    - TOX_ENV=py26-django1.6-drf2.3.8
    - TOX_ENV=py26-django1.6-drf2.4.3
    - TOX_ENV=py26-django1.6-drf3.0
    - TOX_ENV=py27-django1.5-drf2.3.8
    - TOX_ENV=py27-django1.5-drf2.4.3
    - TOX_ENV=py27-django1.5-drf3.0
    - TOX_ENV=py27-django1.6-drf2.3.8
    - TOX_ENV=py27-django1.6-drf2.4.3
    - TOX_ENV=py27-django1.6-drf3.0
    - TOX_ENV=py27-django1.7-drf2.3.8
    - TOX_ENV=py27-django1.7-drf2.4.3
    - TOX_ENV=py27-django1.7-drf3.0
    - TOX_ENV=py32-django1.5-drf2.3.8
    - TOX_ENV=py32-django1.5-drf2.4.3
    - TOX_ENV=py32-django1.5-drf3.0
    - TOX_ENV=py32-django1.6-drf2.3.8
    - TOX_ENV=py32-django1.6-drf2.4.3
    - TOX_ENV=py32-django1.6-drf3.0
    - TOX_ENV=py32-django1.7-drf2.3.8
    - TOX_ENV=py32-django1.7-drf2.4.3
    - TOX_ENV=py32-django1.7-drf3.0
    - TOX_ENV=py33-django1.5-drf2.3.8
    - TOX_ENV=py33-django1.5-drf2.4.3
    - TOX_ENV=py33-django1.5-drf3.0
    - TOX_ENV=py33-django1.6-drf2.3.8
    - TOX_ENV=py33-django1.6-drf2.4.3
    - TOX_ENV=py33-django1.6-drf3.0
    - TOX_ENV=py33-django1.7-drf2.3.8
    - TOX_ENV=py33-django1.7-drf2.4.3
    - TOX_ENV=py33-django1.7-drf3.0
    - TOX_ENV=py34-django1.5-drf2.3.8
    - TOX_ENV=py34-django1.5-drf2.4.3
    - TOX_ENV=py34-django1.5-drf3.0
    - TOX_ENV=py34-django1.6-drf2.3.8
    - TOX_ENV=py34-django1.6-drf2.4.3
    - TOX_ENV=py34-django1.6-drf3.0
    - TOX_ENV=py34-django1.7-drf2.3.8
    - TOX_ENV=py34-django1.7-drf2.4.3
    - TOX_ENV=py34-django1.7-drf3.0

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py26-django1.5-drf3.0
    - env: TOX_ENV=py26-django1.6-drf3.0
    - env: TOX_ENV=py27-django1.5-drf3.0
    - env: TOX_ENV=py27-django1.6-drf3.0
    - env: TOX_ENV=py27-django1.7-drf3.0
    - env: TOX_ENV=py32-django1.5-drf3.0
    - env: TOX_ENV=py32-django1.6-drf3.0
    - env: TOX_ENV=py32-django1.7-drf3.0
    - env: TOX_ENV=py33-django1.5-drf3.0
    - env: TOX_ENV=py33-django1.6-drf3.0
    - env: TOX_ENV=py33-django1.7-drf3.0
    - env: TOX_ENV=py34-django1.5-drf3.0
    - env: TOX_ENV=py34-django1.6-drf3.0
    - env: TOX_ENV=py34-django1.7-drf3.0

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
